### ISSUE TITLE
Can't Build Sitefinity 8.0.5700.0 404

### ISSUE THREAD

**Issue by jonathanread** [Sitefinity/feather#1007]
Just Pulled the feather project and can't build 404 on the Sitefinity 8 nuget. Unable to find version 8.0.5700.0 of package Telerik.Sitefinity.Core

**Comment by Tihomir-Petrov** [comment]
Hey jonathanread,

You've experienced this issue because Sitefinity 8.0 was not publicly released yet (it was released before an hour). On a side note, the Feather team constantly contributes to the 'master' branch and therefore the 'master' branch is not always stable. In this line of thoughts you could pull the source code using a given release tag in order to ensure that you will be able to build the solution.

Regards,
Tihomir
