### ISSUE TITLE
Html Custom Directive

### ISSUE THREAD

**Issue by AlexandreRoba** [Sitefinity/feather#1301]
Hi all is there any sample that demonstrates how to use the sf-htm-field Directive?
I'm trying to use it for couple of days and I'm only buppimg into issues :(

**Comment by Tihomir-Petrov** [comment]
Hey Alexandre,

Can you provide more information about your specific scenario? Where do you want to use the sf-html-field? Also, what are the issues that you faced? 

Regards,
Tihomir

**Comment by AlexandreRoba** [comment]
Thanks for getting back to me.

We need to define several Widgets such as:
Introduction paragrah
Paragraph
Paragraph + List
Paragraph + CTA
(We have more than 20 of them)

All those widgets have several fields but they all have in common a Paragraph field that is a long text and that can contains Rich text (Bold,Italic,links to pages,Bullets....)

When we add the directive sf-html-field on the DesignerView.Content.cshtml and add the the dependencies on the json DesignerView.Content.cshtml such as 
{
    "priority": 1,
    "components" : ["sf-html-field"]
}

Then we add our Javascript file under the MVC/Scripts/<Widget>/designerview-content.js with 
(function ($) {
    var simpleViewModule = angular.module('ParagraphCtrl', ['designer', 'kendo.directives', 'sharedContentServices', 'sfFields', 'sfSelectors']);
    angular.module('designer').requires.push('ParagraphCtrl');
....
})(jQuery);

Then when we start the site, and start the designer. It keeps running and we are getting a Client side error on the JavaScript console that cannot access a SharedContent service.

Regards,

Alex.

**Comment by Tihomir-Petrov** [comment]
Hey Alexandre,

We managed to reproduce the issue on our end. In general there is a bug in the definition of the "sf-html-field" script component. We will try to fix this issue ASAP. The good news is that there is a workaround that can be used until the fix is officially released. We've prepared a code sample that demonstrates how to build a simple content block widget with custom designer that use the "sf-html-field" with a custom angular template. You can find the code sample at https://github.com/Sitefinity/feather-samples/tree/master/SimpleContentBlock . Note that the code sample uses the latest version of Feather (version 1.2.160.0) and that your SitefinityWebApp project should use the same version of Feather (in order to avoid to write binding redirects).

Hope this helps.

Regards,
Tisho

**Comment by David-Heylbroeck** [comment]
Hello, I'm Alex's colleague and I'm facing to a strange behavior. 

I've implemented the html field in a widget and it's working fine when I edit the widget in a page but it's not working when I try to edit the widget in a template. There is no error message either in the javascript consol or in visual studio. 

Do you know anything about that?

Regards,

David.

**Comment by Tihomir-Petrov** [comment]
Hi David,

I tried to reproduce this behavior, but everything worked on my end. Note that I performed the tests using the latest version of Feather (1.2.170.2) and the latest version of the SimpleContentBlock sample (we've upgraded the sample, since we've fixed the issue regarding the HtmlFIeld script component that you initially reported). Will be great if you could provide me with the exact steps that lead to the reproduction of the issue.

Kind Regards,
Tisho

p.s.I recorded a short video regarding the tests that I performed http://screencast.com/t/UoZINUVRLc0

**Comment by David-Heylbroeck** [comment]
I tried a day later and now all works fine. Maybe turning off and on my computer has fixed the problem.

Thanks for your time and your attention

Kind regards,
David
