### ISSUE TITLE
ngSanitize or other Angular Modules best practices

### ISSUE THREAD

**Issue by AlexandreRoba** [Sitefinity/feather#1320]
Hi all,

What would be the best way to include extra angular modules used on the designer views?

thanks,

Alex.

**Comment by dzhenko** [comment]
Hi Alex,

Modules are always preferred as a solution, because of the opportunity for their refusal.

You can define extra modules in external js files (or in the same designerview-yourviewname.js). 
If you use external js files, you must also include them in the DesignerView.YourViewName.json, so they can be loaded.
After that you have to push your custom angular modules in the requires of the designer module ( angular.module('designer').requires.push('yourCustomAngularModule'); )
All the components that your modules expose can be later requested by the YourViewNameCtrl and used inside.

For example, you can see how we implemented https://github.com/Sitefinity/feather-widgets/blob/master/Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Scripts/ContentBlock/shared-content-services.js (the shared-content-services module that is used by the simpleViewModule in our ContentBlock widget).

Kind Regards,
Dzhenko
