### ISSUE TITLE
LoginForm: Claim based SSO scenario

### ISSUE THREAD

**Issue by AlexandreRoba** [Sitefinity/feather#1344]
Dear all,

I have created two SiteFinity web sitse:
Issuer at uri:http://10.0.1.103:7526
RelyingParty at uri:http://10.0.1.103:51803

The scenario using the builtin login screen of sitefinity works fine.
Then I have decided to use a custom page on my issuer wher I have dropped a Login form.
I have updated my Relying party web.config to use as issuer this page (http://10.0.1.103:7526/Login).

When I try to login to the relying party I'm redirected to the Issuer with the following URL
http://10.0.1.103:7526/Login?realm=http%3a%2f%2f10.0.1.103%3a51803&redirect_uri=%2fSiteFinity&deflate=true

I then try to login but I'm not redirected to my Relying party. I'm staying on the issuer login page.

How can I have the login from redirected me to the redirect_uri

Thanks for your help

**Comment by Boyko-Karadzhov** [comment]
Hello Alexandre,

The login form is designed to authenticate users to the current site and it will not issue tokens for other relying parties. Even if it did redirect - the user will not be signed in. It is much like a [Passive Sign-in control](https://msdn.microsoft.com/en-us/library/microsoft.identitymodel.web.controls.federatedpassivesignin.aspx).

Authentication tokens are issued by an HTTP handler outside of the sitemap. It is a SecurityTokenServiceHttpHandler and it is usually listening at _~/Sitefinity/Authenticate/SWT_.

This handler will render a login page that you can edit from _Administration -> Backend pages -> Sitefinity -> Login -> Login_ . Modifications there will affect the login experience of all backend users and also all users that use this Sitefinity instance as a token issuer.

You could inherit from SecurityTokenServiceHttpHandler to create a handler that renders another markup and then you can register it on a different route. You would want to override the SendLoginForm(HttpContextBase context, string message). In order for the handler to issue a token and redirect to the relying party it would expect inputs with names *sf_domain*, *wrap_name*, *wrap_password*, *sf_persistent* to be submitted to it.

In order to leverage the page rendering functionality of Sitefintiy with Feather, a page could be created that has a custom control with the required inputs. The handler can then render the page using *PageManager.RenderPage* mehod.

Please, let me know if this is solution works for you.

Regards,
Boyko

**Comment by AlexandreRoba** [comment]
Hi Boyko,

Thanks for the clarification. I'll try to create a custom handlers and  render the result with the PageManager. I was expecting to leverage Feather widget possibilities and SiteFinity SSO to create a custom login page on our SiteFinity IdentityServer for each of the relying parties... The proposed solution seems more complex to handle in terms of custom layout for the different relying parties. :( 

We are currently creating a fronted Identity Server for all the front end users of our different sites. I was not aware that the SSO scenario was made towards Backend users.

Regards,

Alexandre.

**Comment by Boyko-Karadzhov** [comment]
Hello Alexandre,

The default backend login goes through the SSO login form while frontend users usually use a login widget. When SSO is configured all users authenticate at the same form on the token issuer and that is the form we are used to see for backend authentication although it doesn't matter if the user is a backend one or not.

For a simpler solution you could modify the Login page from "Backend pages" in the administration and drag a custom widget there that renders different layout based on the relying party parameter. The POST action is handled by the HTTP handler, the widget just has to submit.

Having custom HTTP handlers at other routes that render different pages is also ok. This way the pages could be based on different templates.

Regards,
Boyko
