### ISSUE TITLE
Newest Nuget Package issues with 7.3

### ISSUE THREAD

**Issue by joelkinzel** [Sitefinity/feather#1449]
I've just followed the directions to install Project Feather on a SF7.3 install. After doing the initial steps of enabling it on the back end, everything worked fine. 

Then I went through the steps of removing the "ResourcePackages" folder, and downloading the newest version from the Telerik Nuget repository. After doing that, I'm getting the following error: 

"Could not load file or assembly 'Telerik.Sitefinity, Version=8.0.5700.0, Culture=neutral, PublicKeyToken=b28c218413bdf563' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)" 

Looks like it is looking for some v8.0 stuff, which obviously isn't going to found in a 7.3 install.

**Comment by Boyko-Karadzhov** [comment]
Hello joelkinzel,
Feather 1.2 and above is compatible with Sitefinity v8.0 and the internal releases on it. The latest Feather that supports Sitefinity v7.3 is 1.1.110.0. We continuously improve Sitefinity's extensibility to enable us to implement greater features for Feather. Because of this usually the latest Feather requires the latest official version of Sitefinity.

Regards,
Boyko

**Comment by mariushm** [comment]
Hi,

I've updated the prerequisites in the [Getting Started](../wiki/Getting-Started) guide and added a note about Sitefinity 7.3. Apologies for the confusion.

We strongly recommend using the latest Feather and Sitefinity 8.0. If you won't be upgrading any time soon and need us to add 7.3 support, please vote in [our poll on Google community](https://plus.google.com/u/0/105160192481296018371/posts/2zRTuYmYvYs)

Best regards,
Mariush
