### ISSUE TITLE
How to identify the source of an error when creating a custom designer view?

### ISSUE THREAD

**Issue by AlexandreRoba** [Sitefinity/feather#145]
Hello all,

I've tried to follow the "Create a custom designer View" documentation page. I have added two cshtml item to my MVC\Views\Widget01\ folder. 
DesignerView.Settings.cshtml
DesignerView.Title.cshtml

Those MVC are bloody simple:
&lt;input ng-model="properties.Message.PropertyValue" type="text" /&gt;

Where message is a property of my controler (I'm using the default Thunder MVC Widget template without a designer). I can clearly see my designers showing as button on the popup designer but when I click on any of them, I'm getting the error "Error! Could not load designer view!"...

Any recommendation how I could investigate this issue?

Thanks for any help.

**Comment by mariushm** [comment]
Hi,

The problem is that Thunder MVC widget templates don't include references to the Feather assemblies   and the designer views created by the new convention are not found. 

You need to add the following to **AssemblyInfo.cs**:

``` C#
using Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Controllers.Attributes;
[assembly: ControllerContainer] 
```
We will improve the documentation to explain this better until Thunder is also updated with Feather-based templates.

**Comment by AlexandreRoba** [comment]
Thanks for that. Indeed that solved my issue.
