### ISSUE TITLE
Comments: you are not able to login in MS/ML

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather#1682]
1. Create a site ( MS/ML - bulgarian default language)
2. Create a login page
3. Set login page in Manage site for the site
4. Create news item 
5. Check setting Requires authentication
6. Create a page with news widget
7. Navigate the page with anonymous user
8. Try to login

Actual result is: You are not able to login

**Comment by Boyko-Karadzhov** [comment]
Could be caused by output cache. If you have not configured a login page for the site and navigate to the news item - it will be cached without the login page url. After setting login page in the backend the cache will NOT be invalidated and you will still not receive login url until you republish the page.
