### ISSUE TITLE
Feather Content block: "Insert a link" > "Page from this site" - current language should be selected

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#186]
Branch: master
Pre: you have multisite enabled, default site is monolingual and second site is multilingual (EN default, DE languages)
Steps to reproduce:
1. switch to second site
2. open DE page
3. drag and drop Content block widget
4. open designer
5. open link selector
6. select "Page from this site"
As a result: second site and DE language should be selected
NOTE: related to https://github.com/Sitefinity/feather-widgets/issues/203 (Link selector > Page from this site - the current site is not selected in the dropdown) AND https://github.com/Sitefinity/feather/issues/189 (Link Selectors: Switching between sites is causing problems in language dropdown)

**Comment by NadezhdaPetrova** [comment]
Behavior: Site 1 (default) with EN (default) and DE; Site 2 with EN and BG (default)

Case 1: Open EN page in Site 1. Site 1 is selected from the sites dropdown and the page language (EN) is selected from the languages dropdown
Change to Site 2. Then the selected language must be EN, because you are in EN page

Case 2: Open BG page in Site 2. Site 2 is selected from the sites dropdown and the BG is selected from the languages dropdown (this is the language of the current page)
Change to Site 1. Then EN will be selected for language because Site 1 does not have BG language and then will select the default language for Site 1 (EN).
