### ISSUE TITLE
Major bug in image gallery (MVC)

### ISSUE THREAD

**Issue by ckoch1979** [Sitefinity/feather#1865]
1. Place the MVC image gallery widget in a bootstrap template
2. Select "lightbox gallery"
3. Select an image size different from "original size"
4. Open the page at frontend and click on a picture

Result: The original image-size is opened. If you look at the url of the thumbnail you can see that the url of the original picture is rendered and not the url of the other image size.

Is there a workaround?

**Comment by ElenaGaneva** [comment]
Hello ckoch1979,

The behavior that you mentioned is by design. When you use overlay list view then we are not actually showing detail page therefore the settings for detail page are not used.

 In case you want to change the default behavior you can create new html helper that receives as argument the Sitefinity image and then provides the resized thumbnail URL like this:
image.ResolveThumbnailUrl([thumbnailName], true);
 
Then you can copy the content of [OverlayGallery template]( https://github.com/Sitefinity/feather-widgets/blob/master/Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.OverlayGallery.cshtml) inside your SitefinityWebApp/Mvc/Views/ImageGallery and modify the value of attribute *data-detail-url* of the image in order to be resolved from the new html helper that you have already created.

If you need any further assistance on this, let me know.

Regards,
Elena

**Comment by ckoch1979** [comment]
Hallo Elena,

I think you have to change this behavior by default. If an user selects a certain image size, he wants to render that size indepedent from the type of gallery. The widget does not do what it should do, therefore it is a malfunction.

Regards,
Christian

**Comment by ckoch1979** [comment]
One thing I would like to add. The behaviour you described does not match the behavior of the web forms gallery, therefore it is a bug or better said a malfunction. It does not make sense to render the original Image if you select the thumbnail.

**Comment by ElenaGaneva** [comment]
Hello ckoch1979,

Thank you for your feedback. I am adding this in our backlog so we can fix it in the product. You will be notified as soon as the fix is released.

Regards,
Elena

**Comment by ckoch1979** [comment]
Hello Elena,

that is great!

Could you provide me some help with the workaround you mentioned?

Regards,
Christian Koch

Von: Elena Ganeva [mailto:notifications@github.com]
Gesendet: Dienstag, 2. Juni 2015 10:29
An: Sitefinity/feather
Cc: Christian Koch
Betreff: Re: [feather] Major bug in image gallery (MVC) (#1865)


Hello ckoch1979,

Thank you for your feedback. I am adding this in our backlog so we can fix it in the product. You will be notified as soon as the fix is released.

Regards,
Elena

**Comment by ckoch1979** [comment]
Thanks for the quick fix!



Am 04.06.2015 um 13:07 schrieb SlaveyaShtereva <notifications@github.com<mailto:notifications@github.com>>:


Closed #1865<https://github.com/Sitefinity/feather/issues/1865>.

-
