### ISSUE TITLE
Classification: All tags are displayed even if they are not assigned to images in a gallery

### ISSUE THREAD

**Issue by ckoch1979** [Sitefinity/feather#1869]
The new MVC Tag widget does not work properly.

1. Create two image libraries named cats and dogs 
2. Upload one picture to every library
3. Assign the tag dog to the picture in library dogs and assign the tag cats to the image in library cats
4. Drag an image gallery widget to a new page and just display the images of the gallery dogs
5. Add the tag widget 

Result: The tags cat and dog are displayed although only images with the tag dog are selected.

The problem is, that all tags show up independent from the images that are displayed.

**Comment by Boyko-Karadzhov** [comment]
Hello,

The classification widgets are not aware of how the other widgets on the page are configured. Widgets are independent from each other by design. In this case if you select "cats" from the Tags widget you will see a page with images that have both "cats" and "dogs" tags on them.

To generate links for tags that are dependent on the current state of the image gallery widget I'd suggest implementing an HTML helper and placing it inside the gallery's template.

Regards,
Boyko
