### ISSUE TITLE
Comments widget : Add edit and report abuse function in the frontend widget.

### ISSUE THREAD

**Issue by David-Heylbroeck** [Sitefinity/feather#1876]
Hello,

For our current project we need to add an edit function (a user can edit his own comments) and a report abuse function reachable by the public user.

Is it possible?

Do you have some code example to do that?

David.

**Comment by ElenaGaneva** [comment]
Hi David,

Current implementation of the Comments allow editing and reporting abuse through backend *Comments* section only. Actually we have restricted the CommentsWebService endpoint to allow comments edit for backend users only.
 Still the functionality that you requested can be achieved like this:

1)Register your own web service that will handle edit and mark as spam functionalities while updating comments. In order to do this you can add new ServiceStack plugin as explained [here]( https://gist.github.com/hardye/7021091) or use [*Sitefinity Thunder*](http://docs.sitefinity.com/sitefinity-thunder-automate-you-development) to auto generate new *Sitefinity Web Service*. In this service you can modify comments as explained here:
http://docs.sitefinity.com/for-developers-modify-comments 

2)Create new view for the Comments widget in order to provide UI for editing and reporting abuse:
 * Create new view Comments.EditView.cshtml inside your SitefinityWebApp/Mvc/Views/Comments folder. You can base this view on the [default one]( https://github.com/Sitefinity/feather-packages/blob/master/Bootstrap/MVC/Views/Comments/Comments.Default.cshtml).
* Edit the div with *data-sf-role="single-comment-template"* and add in it “Edit” and “Report abuse” buttons. This way they will be visible next to every submitted comment.
* Add textbox for editing comments message and *Done editing* button next to the following element and switch which one is visible when clicking edit:
````
<p data-sf-role="comment-message"></p>

``` 

3)Add your own JavaScript file in order to implement the client side logic. 
* Register the new js file in the template from step 2.
* Handle clicking “Done editing” and “Report abuse” buttons and make request to the web service from point 1.

If you need any further assistance for this implementation do not hesitate to contact us. 

Furthermore I am adding this request to our backlog. 

Regards,
Elena

**Comment by David-Heylbroeck** [comment]
Hi Elena,

I create my servicestack plugin and I override the Comments.Default view to add my edit button.

But I have to show the edit button only if it is the user who created the comment that is logged, but I don't know how to do that, 
- How I get the comment author id in the view? 
- How I get the comment key?
- Do you have a way to get the id of the logged user in the view (If it's not possible I can create a service to do that but maybe you have an out of the box property for that)?

Thanks in advance for your help.

Regards, 
David

**Comment by ElenaGaneva** [comment]
Hi David,

In order to get the comments key and comments author you can edit the comments JavaScript and customize the logic for populating comments list markup. This could be achieved like this:

* Create js file named *comments-list.js* inside your folder SitefinityWebApp/Mvc/Scripts and copy the content of the default script in it:
https://github.com/Sitefinity/feather-widgets/blob/master/Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js 
* Edit the *createCommentMarkup* function by adding your custom logic for hiding and showing the edit button. In this method you have access to the comment return by the service, so you can access its *Key* and author’s *Email*

Regarding your third question – I can suggest you expose your own endpoint in order to get the information about current user and call the service through JavaScript. This way you won’t have to worry that the sensitive user information can be cached.

Please feel free to ask if you need any additional details.

Regards,
Elena
