### ISSUE TITLE
Link Selectors: Switching between sites is causing problems in language dropdown

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#189]
1. Make multisite multilingual environment with different languages for each site (first site: EN default and DE, second site: EN default and BG)
2. Open Content block - > Link selector - > Page in this site option
3. Select first site and DE language
4. Pages are listed in page selector
5. Switch to second site in Site dropdown (second site does not have DE language)
As a result: Language dropdown is empty, all pages appear not translated and if you list languages dropdown it is not looking fine (see screenshot http://screencast.com/t/NkqcfdaR3KVP)
When switching sites from Site dropdown, Languages dropdown should be repopulated with default language of currently selected site in Sites dropdown
NOTE: related to https://github.com/Sitefinity/feather/issues/186 (Feather Content block: "Insert a link" > "Page from this site" - current language should be selected)

**Comment by NadezhdaPetrova** [comment]
Behavior: Site 1 (default) with EN (default) and DE; Site 2 with EN and BG (default)

Case 1: Open EN page in Site 1. Site 1 is selected from the sites dropdown and the page language (EN) is selected from the languages dropdown
Change to Site 2. Then the selected language must be EN, because you are in EN page

Case 2: Open BG page in Site 2. Site 2 is selected from the sites dropdown and the BG is selected from the languages dropdown (this is the language of the current page)
Change to Site 1. Then EN will be selected for language because Site 1 does not have BG language and then will select the default language for Site 1 (EN).
