### ISSUE TITLE
Registration : unable to display/save custom fields 

### ISSUE THREAD

**Issue by Sylvain-S** [Sitefinity/feather#2014]
1. Administration > Users > Manage Profile Types and add custom fields to the basic profile: Company, Function, ZipCode, Country, Language (all Short Texts)

2. Create a page and add Registration widget

3. Edit "ProfileBindings" property of the widget with the following : [{ProfileType: 'Telerik.Sitefinity.Security.Model.SitefinityProfile',Properties: [{ Name: 'FirstName', FieldName: 'FirstName', Required: true },{ Name: 'LastName', FieldName: 'LastName', Required: true }, {Name:'About', FieldName:'About' }, {Name:'Company', FieldName:'Company' }, {Name:'Function', FieldName:'Function'}, {Name:'ZipCode', FieldName:'ZipCode'}, {Name:'Country', FieldName:'Country'}, {Name:'Language', FieldName:'Language'} ]}]

4. Override the view Registration.RegistrationForm.cshtml and add html to get new properties:

         <div class="form-group">
            <label>
                @Html.Resource("EditProfileFunction")
            </label>
            @Html.TextBoxFor(m => m.Profile["Function"], new { @class = "form-control" })
        </div>

5.Widget Controller gives an error : 

An exception of type 'System.Collections.Generic.KeyNotFoundException' occurred and was caught.
-----------------------------------------------------------------------------------------------
06/15/2015 15:27:16
Type : System.Collections.Generic.KeyNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Message : The given key was not present in the dictionary.

**Comment by dzhenko** [comment]
Hi Sylvain-S,

Unfortunately the "Profile" property is a dictionary and TextBoxFor(m => m.Profile["Function"] ....) will not work, because the way ASP.NET MVC binds a model to dictionary is more specific - you can take a look at [this article](http://www.hanselman.com/blog/ASPNETWireFormatForModelBindingToArraysListsCollectionsDictionaries.aspx). 

However, there is an easy workaround - just use @Html.TextBox("Profile[Function]") instead.

Kind Regards,
Dzhenko

**Comment by Sylvain-S** [comment]
Hello @dzhenko ,

Great, thank you very much for the tip !

Best,
Sylvain
