### ISSUE TITLE
@Html.StyleSheet doesn't resolve relative

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#2052]

**Comment by sitefinitysteve** [comment]
![renderstylesheet](https://cloud.githubusercontent.com/assets/1542376/8258264/91625b96-1681-11e5-9c73-2f1c8894b3f8.PNG)

**Comment by sitefinitysteve** [comment]
Ooh...another thing to note is that in Hybrid it renders the <link> inline where it's defined in the widget...is there no way to get it to render in the head of the masterpage or something...or...am I missing how to do it?

**Comment by manev** [comment]
The "Html.StyleSheet" doesn't handle relative paths that are starting with tilde by default. You have two options: Remove the tilde character or use the "Url.WidgetContent" inside the "Html.StyleSheet". So in your case the code should look like:
@Html.StyleSheet(Url.WidgetContent("~/Temp/Placements/pdr.min.css"))

As for your second question - the "@Html.StyleSheet" method has a version with second parameter (sectionName), which refers to the place where the script will be rendered. Follow the code listed bellow in order to render your script in the page head:
@Html.StyleSheet(Url.WidgetContent("~/Temp/Placements/pdr.min.css"), "head")

**Comment by sitefinitysteve** [comment]
Problem is it's a hybrid mode masterpage...there are no sections

**Comment by sitefinitysteve** [comment]
Can anyone comment on this one re: Masterpage no "Sections"?

**Comment by mariushm** [comment]
Hi Steve,

The sections functionality is designed to work only for .cshtml based templates, it doesn't work for master pages, unfortunately. 

Mariush
