### ISSUE TITLE
Tag Cloud: Where Is It?

### ISSUE THREAD

**Issue by MerrittMelker** [Sitefinity/feather#2186]
eom

**Comment by ElenaGaneva** [comment]
Hi Merritt,

Since version 1.2.230.0 of Feather we included *Tags* widget that suports different default templates for displaying the tags:

 * *SimpleList*  
The widget displays tags in a vertical list.
 * *TagCloud*  
The system tags in a horizontal list. The more items are tagged with a tag, the larger font the system uses to display this tag.
 * *CloudList*  
The system tags in a vertical list. The more items are tagged with a tag, the larger font the system uses to display this tag.

To take advantage of the build-in styling you can drag the *Tags* widget (in the toolbox under *Classifications* section) on page based on *Bootstrap* package. For more information about this tempaltes you can check the docuemntaion of the widget:

https://github.com/Sitefinity/feather/wiki/MVC-Tags-widget 

You can see the source of TagCloud template for bootstrap in ResourcePackages folder under Bootstrap/Mvc/Views/FlatTaxonomy or [here](https://github.com/Sitefinity/feather-packages/tree/master/Bootstrap/MVC/Views/FlatTaxonomy)

Please let me know if you need any additional details on the matter.

Regards,
Elena

**Comment by MerrittMelker** [comment]
Sorry, my team relayed information that wasn't totally accurate to me. Thanks.
