### ISSUE TITLE
Check for scripts

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#2266]
To improve the widget editor load can we not test to see if kendo\bootstrap scripts are already loaded on the page before sending them all back down to the page (again)?

**Comment by ElenaGaneva** [comment]
Hello Steve,

Thank you for your feedback. We have made improvements in Feather scripts and styles loading prior to 11.0+ releases in order to improve the loading time and developer experience.

To contribute to this project please submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.

Regards,
Elena
