### ISSUE TITLE
HTML editor display issues when more than one editor is on the page

### ISSUE THREAD

**Issue by ericadam** [Sitefinity/feather#2358]
https://github.com/Sitefinity/feather/blob/e3f9622fba566c1e826d6ceaaaec746be3e0dc56/Telerik.Sitefinity.Frontend/client-components/fields/html-field/sf-html-field.js

On line 242 in the scope.toggleHtmlView function, the jQuery selector is way too broad and selects all matching items on the page. 

In Angular directives you want to limit such selectors to the element. A corrected line might read:
element.find(".js-htmlview").addClass("active");

I have not audited the full source for more instances like this.

**Comment by bentheartist** [comment]
confirming that the broad jQuery selectors are a problem throughout the the file, and further that the use of variables within the scope of the directive function (lines 7 - 10) is problematic, since it creates a closure... all instances of the editor share these references, whose final assignment is from the last widget created (kendoWidgetCreated handler on line 30). many symptoms result from these shared variables, one example being that the toggleAllTools function will toggle the toolbar commands for the last editor on the page, no matter which editor makes the call.

changing the directive-scoped-variables to instead be properties of the scope resolves that part of the problem; combining this with more specific queries entirely resolves issues from multiple html editors on the same page, for me.

**Comment by ElenaGaneva** [comment]
Hello ericadam,

This is fixed in latest versions of Sitefinity 9.2+.

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
