### ISSUE TITLE
Only one content placeholder allowed in the layout file

### ISSUE THREAD

**Issue by JohnAbassian** [Sitefinity/feather#59]
The SfPlaceHolder helper wraps the content placeholders with a div with runat="server" and a hardcoded id, making it impossible to have more than one content placeholder on a layout. 

    public static MvcHtmlString SfPlaceHolder(this HtmlHelper helper, string containerName = "Body")
        {
            var htmlString = string.Format(System.Globalization.CultureInfo.InvariantCulture, "<div class='sfPublicWrapper' id='PublicWrapper' runat='server'><asp:contentplaceholder id='{0}' runat='server' /></div>", containerName);

            return new MvcHtmlString(htmlString);
        }

**Comment by mariushm** [comment]
The bootstrap grid widgets are currently available by default for all packages, because they exist as embedded resources in the assembly file. When you try to use them on a layout from another package, Sitefinity doesn't find the corresponding file in the file system and takes them from the assembly.
The current behavior is indeed confusing and we be will looking how to improve it in the future.

**Comment by mariushm** [comment]
Hi,

As an improvement to the behavior discussed above, we are now registering all grid widgets from the GridSystem\Templates folder automatically for each package. The improvement was just shipped with today's weekly release. 

Mariush

**Comment by jacques-hoventer** [comment]
I'm hoping to revive this thread because I'm experieincing similar issues to what John mentions in his comment: https://github.com/Sitefinity/feather/issues/59#issuecomment-62165341

Are you 'supposed' to create a separate Layout file and then import it into Sitefinity? I can see the layout.cshtml file in the ResourcePackages/Bootstrap/MVC/Views/Layouts folder which I tried to copy into the App_Data\Sitefinity\WebsiteTemplates\MyTemplate\App_Master folder, but when I try to create a new template in Sitefinity and base it on this physical file Sitefinity doesn't allow you to select it presumably because it's not a dotMaster file? 

Can someone point me to a link perhaps that explains how this should be done? 

Thanks

**Comment by rhullah** [comment]
It's personal preference (and sometimes requirements of the project) on wether you create a separate layout file or just use one of the existing ones.  Best practice is to either create your own Feather Package (to live next to Bootstrap/SemanticUI/Foundation) either from scratch or by copying an existing one, or to just create your own Layout file (from scratch or a copy of existing) and place it next to an existing layout file.  That way updates to Feather don't overwrite changes you've done to the layout file.

You should be placing Feather layouts in the `ResourcePackages/[PackageName]/MVC/Views/Layouts` folder, not in your `App_Data` folder.

**Comment by jacques-hoventer** [comment]
So placing it in the  ResourcePackages/[PackageName]/MVC/Views/Layouts folder... how does Sitefinity make use of it? I assume if I added a file called MyCustomMVCLayout.cshtml in that folder, Sitefinity - on start up- would scan that folder and find it, but what does it do with it? 

We'll need to create a bunch of custom template files for specific scenarios but they'll need to be based on this MyCustomMVCLayout.cshtml file. Normally I would create a new template and browse to the physical Master page file. How does this work for this Layout file in this folder?

**Comment by jacques-hoventer** [comment]
Okay I noticed after a restart that the new template is there as well as the default.cshtml that comes with the Bootstrap package. Adding the Bootstrap grid layout items to the template in Sitefinity works as expected but what I did expect is that my custom WebForms widget doesn't show up in the toolbox for this template. 

Is the idea with Hybrid that you're supposed to be able to use either WebForms or MVC based widgets on either pages or templates so long as the tempate was configured to be Hybrid?

**Comment by mariushm** [comment]
To enable the hybrid capabilities you need to base your pages on a template which is configured so. 
Go to design -> page templates and create a new template with "MVC and Web Forms (hybrid)" option selected as Web Framework in Advanced settings. This will enable both Web Forms and MVC widgets in the toolbox for the pages using this template.
If the hybrid template is based on a page template from the Bootstrap package, then the Bootstrap grid widgets will also work.

**Comment by jacques-hoventer** [comment]
My apologies, I forgot that step and it does exactly what you say it does. The only oddity now is that for the built-in widgets it shows both the MVC and standard widgets which would be confusing to the user. Is there a way to hide the standard widgets and force the user to use the MVC widgets instead?

**Comment by mariushm** [comment]
Yes, you can edit the toolboxes.config file to control which widgets are shown/hidden - just set enabled to "false" for the items you want to hide.

**Comment by jacques-hoventer** [comment]
Thanks for all the help, I got everything working.
